### ISSUE TITLE
通用依赖安装有问题

### ISSUE THREAD

**Issue by yzxj3180** [youshandefeiyang/SSRSpeedN-Mod#5]
已经正确安装Python和获取管理员权限  系统是win11 安装依赖后全部报错。

Requirement already satisfied: pip in c:\users\yuanh\appdata\local\programs\python\python310\lib\site-packages (21.2.3)
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\yuanh\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\cli\base_command.py", line 173, in _main
    status = self.run(options, args)
  File "C:\Users\yuanh\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\cli\req_command.py", line 203, in wrapper
    return func(self, options, args)
  File "C:\Users\yuanh\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\commands\install.py", line 315, in run
    requirement_set = resolver.resolve(
  File "C:\Users\yuanh\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 94, in resolve

**Comment by youshandefeiyang** [comment]
没问题哦，检查你自己的本地网络和vc++运行库

**Comment by skylover007** [comment]
我也是win11，装python3.10.0的话问题跟你一样，试试3.9.6吧

**Comment by yzxj3180** [comment]
vc++最低应该用什么版本？
